name       : gnome-system-monitor
version    : 3.26.0
release    : 12
source     :
    - https://download.gnome.org/sources/gnome-system-monitor/3.26/gnome-system-monitor-3.26.0.tar.xz : f848a8c2ca5e164cf09d3a205dd49e4e4bf4b60d43b0969c10443eb519d0e6b3
license    : GPL-2.0
component  : desktop.gnome
summary    : A system monitor GUI application for GNOME
description: |
    A system monitor GUI application for GNOME
builddeps  :
    - pkgconfig(atkmm-1.6)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libwnck-3.0)
    - itstool
clang      : no
setup      : |
    %configure --enable-systemd --enable-broken-wnck
build      : |
    %make
install    : |
    %make_install
    rm $installdir/usr/share/applications/gnome-system-monitor-kde.desktop
