name       : gnome-system-monitor
version    : '41.0'
release    : 23
source     :
    - https://download.gnome.org/sources/gnome-system-monitor/41/gnome-system-monitor-41.0.tar.xz : c7fc44c61949b794b0289968ebbbcc0c15f8cfc3d9e45bfaa81ed45c12139e5f
license    : GPL-2.0-only
component  : desktop.gnome
summary    : A system monitor GUI application for GNOME
description: |
    A system monitor GUI application for GNOME
builddeps  :
    - pkgconfig(atkmm-1.6)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libwnck-3.0)
    - itstool
setup      : |
    %patch -p1 < $pkgfiles/0001-Revert-use-of-libhandy.patch
    %patch -p1 < $pkgfiles/0001-Ensure-headerbar-is-set-as-the-titlebar.patch
    %meson_configure -Dwnck=true
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm $installdir/usr/share/applications/gnome-system-monitor-kde.desktop
