name       : gnome-system-monitor
version    : 3.22.2
release    : 10
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-system-monitor/3.22/gnome-system-monitor-3.22.2.tar.xz : 68a5b097157a6e445fc2467cbaecfede77d00b774c93e8aa69b6f784055dc982
license    : GPL-2.0
component  : desktop.gnome
summary    : A system monitor GUI application for GNOME
builddeps  :
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(atkmm-1.6)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libwnck-3.0)
    - itstool
clang      : no
description: |
    A system monitor GUI application for GNOME
setup      : |
    %configure --enable-systemd \
               --enable-wnck
build      : |
    %make
install    : |
    %make_install
    rm $installdir/usr/share/applications/gnome-system-monitor-kde.desktop
