name       : gnome-system-monitor
version    : 3.20.1
release    : 9
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gnome-system-monitor/3.20/gnome-system-monitor-3.20.1.tar.xz : 9b23ab443fd92050b95c03a0ab321bbd41696a0ffc89c06e79c8798dca0a44f9
license    :
    - GPLv2+
summary    : A system monitor GUI application for GNOME
builddeps  :
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(atkmm-1.6)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libwnck-3.0)
    - itstool
clang      : no
description: |
    A system monitor GUI application for GNOME
setup      : |
    %configure --enable-systemd \
               --enable-wnck
build      : |
    %make
install    : |
    %make_install
    rm $installdir/usr/share/applications/gnome-system-monitor-kde.desktop
