name        : gnome-system-monitor
version     : 3.18.0
release     : 7
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gnome-system-monitor/3.18/gnome-system-monitor-3.18.0.tar.xz : 19d4322a8b7f932b2bb8f3dd0b21a20b0cd4b7dafb55fcdfbd2bc8c109b02b10
license     :
    - GPLv2+
summary     : A system monitor GUI application for GNOME
builddeps   :
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(atkmm-1.6)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libwnck-3.0)
    - itstool
clang       : no
description : |
    A system monitor GUI application for GNOME
setup      : |
    %configure --enable-systemd \
               --enable-wnck
build      : |
    %make
install    : |
    %make_install
    rm $installdir/usr/share/applications/gnome-system-monitor-kde.desktop
