name       : gnome-system-monitor
version    : '44.0'
release    : 26
source     :
    - https://download.gnome.org/sources/gnome-system-monitor/44/gnome-system-monitor-44.0.tar.xz : c2bab7eddba92827c4c8de44293e7e3c84c9e5076f31985887ff8969cec45e6e
license    : GPL-2.0-only
component  : desktop.gnome
summary    : A system monitor GUI application for GNOME
description: |
    A system monitor GUI application for GNOME
builddeps  :
    - pkgconfig(atkmm-1.6)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(libhandy-1)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libwnck-3.0)
    - itstool
setup      : |
    %meson_configure -Dwnck=true
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm $installdir/usr/share/applications/gnome-system-monitor-kde.desktop
