name        : gnome-system-monitor
version     : 3.16.0
release     : 5
source      :
    - http://ftp.acc.umu.se/pub/gnome/sources/gnome-system-monitor/3.16/gnome-system-monitor-3.16.0.tar.xz : 00936e8b5d29fc01cd6daf6c119242877d81b2dcca33fb0ee9ce4adec8675391
homepage    : https://help.gnome.org/users/gnome-system-monitor/3.12/
license     :
    - GPLv2+
summary     : A system monitor GUI application for GNOME
builddeps   :
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(atkmm-1.6)
    - pkgconfig(librsvg-2.0)
    - itstool
clang       : no
description : |
    A system monitor GUI application for GNOME
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    rm $installdir/usr/share/applications/gnome-system-monitor-kde.desktop
