name       : gnome-system-monitor
version    : '42.0'
release    : 25
source     :
    - https://download.gnome.org/sources/gnome-system-monitor/42/gnome-system-monitor-42.0.tar.xz : 13239d22032201a22bd29833c575b684816700d2de168a1530223577c5c075dc
license    : GPL-2.0-only
component  : desktop.gnome
summary    : A system monitor GUI application for GNOME
description: |
    A system monitor GUI application for GNOME
builddeps  :
    - pkgconfig(atkmm-1.6)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(libhandy-1)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libwnck-3.0)
    - itstool
setup      : |
    %meson_configure -Dwnck=true
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm $installdir/usr/share/applications/gnome-system-monitor-kde.desktop
