name       : gnome-system-monitor
version    : '40.0'
release    : 19
source     :
    - git|https://gitlab.gnome.org/GNOME/gnome-system-monitor : d4da0b068eae0a62b2f1d765f9f0593f3f1b5869
license    : GPL-2.0-only
component  : desktop.gnome
summary    : A system monitor GUI application for GNOME
description: |
    A system monitor GUI application for GNOME
builddeps  :
    - pkgconfig(atkmm-1.6)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libwnck-3.0)
    - itstool
setup      : |
    %patch -p1 < $pkgfiles/0001-Revert-use-of-libhandy.patch
    %meson_configure -Dwnck=true
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm $installdir/usr/share/applications/gnome-system-monitor-kde.desktop
