name       : gnome-system-monitor
version    : 3.24.0
release    : 11
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gnome-system-monitor/3.24/gnome-system-monitor-3.24.0.tar.xz : c32b45062411aaef06681e5e28fd2c24ea8b362168bae83992944ec8e02063f4
license    : GPL-2.0
component  : desktop.gnome
summary    : A system monitor GUI application for GNOME
description: |
    A system monitor GUI application for GNOME
builddeps  :
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(atkmm-1.6)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libwnck-3.0)
    - itstool
clang      : no
setup      : |
    %configure --enable-systemd --enable-broken-wnck
build      : |
    %make
install    : |
    %make_install
    rm $installdir/usr/share/applications/gnome-system-monitor-kde.desktop
